### ISSUE TITLE
ADD Named Individuals for oa:Motivation

### ISSUE THREAD

**Issue by amberbilley** [ld4l-labs/ontology#41]
PR #36
bibliotek-o change requests by the ArtFrame Community for 2017 Q2.

ADD Named Individuals for oa:Motivition
bib:specifyingSupplementaryContent
bib:specifyingBiographicalData
bib:specifyingAdministrativeHistory

Justification:

bib:specifyingSupplementaryContent 
As narrower term under bib:specifying
See 504: http://www.loc.gov/marc/bibliographic/bd504.html
Different from bf:supplementaryContent and class bf:SupplementaryContent when that supplementary material is a resource in itself, versus a few pages of index, bibliography, discography, etc, 
 
Under bib:specifying
    bib:specifyingBiographicalData 
            bib:bib:specifyingAdministrativeHistory

**Comment by sfolsom** [comment]
I understand why there was a recommendation for specifyingBiographicalData, but I'm reluctant to map it as an annotation off a Work, Instance, or Item. It seems like something that should be an rdfs:comment, skos:note off the thing it's actually describing; this is hard to do when it comes to mapping, but perhaps this can be done manually. How prevalent are 545s? Having said that, I don't want to obstruct this if others are convinced we need it now; we can always migrate to the appropriate agent after the fact.

**Comment by rjyounes** [comment]
Here's a nice visualization of frequency of occurrence of MARC fields: http://experimental.worldcat.org/marcusage/viz/starburst-tags.html

545 is so small that I can't get my cursor on it, but it's somewhere below .3%.

@sfolsom Your proposal makes sense to me. Probably the same applies to administrative history, which is also in 545.  Supplementary content for non-resources makes sense.

**Comment by amberbilley** [comment]
MARC 504 NOT MARC 545. 

MARC 504 is very common. 13.3% of MARC records contain them. 

Specifying (or making a note about) biographicalData is very different than a resource being biographical data. We want to make notes about the SupplementaryContent, not declare the SupplementaryContent itself.

**Comment by sfolsom** [comment]
Sorry, I'm confused. Are you proposing bib:specifyingBiographicalData (545) or bib:specifyingBibliographicalData (504)? The list above says ADD bib:specifyingBiographicalData. If this about biographical data for persons, etc. from the 545, then my original comment stands. If it's about bibliographical data, then sure no problem. :)

**Comment by eslao** [comment]
@amberbilley, correct me if I'm wrong, but, the content of bib:specifyingBiographicalData would note the *presence* of biographical data or administrative history, and would not be the biographical data administrative history itself  -- right? (I've never used 504 this way, but I only ever did the most vanilla cataloging.) Should this be a narrower motivation under bib:specifying, or should it be directly under oa:describing?

With bib:specifyingAdministrativeHistory, would you be describing the administrative history of an item or instance? (Rather than describing the administrative history of an organization, like in a 545 1_?)

**Comment by melanieWacker** [comment]
These proposals originated from the mapping work. The first, specifyingSupplementaryContent is based on the 504, is basically a note that the item includes some sort of supplementary information such as a bibliography, filmography or discography. As Amber said, this note is VERY common we need to be able to map it to something.

The second, specifyingBiographicalData and specifyingAdministrativeData indeed resulted from mapping the 545, first indicators 0 and 1. This element is primarily used in archival cataloging, to give some background on the person or corporate body who is the main focus of the collection. So think archival description level here.

**Comment by eslao** [comment]
Thanks, @melanieWacker. So, this makes sense, but perhaps we should discuss whether we'd want to apply @sfolsom's suggestion (originally about bib:specifyingBiographicalData, where it doesn't seem applicable, now) to bib:specifyingAdministrativeHistory? "It seems like something that should be an rdfs:comment, skos:note off the thing it's actually describing" -- in this case the person or corporate body itself? Can you point us to an example?

**Comment by melanieWacker** [comment]
Yes, @eslao  -- as @amberbilley mentioned we also ran across it when looking at notes and annotations in art. So here are a few 545 examples provided by the ArtFrame group:
http://www.loc.gov/pictures/item/ggb2004003493/marc/
http://www.loc.gov/pictures/item/2006678412/marc/
http://francine.clarkart.edu/search/?searchtype=t&SORT=D&searcharg=Mrs.+Clark

**Comment by rjyounes** [comment]
@eslao As a general rule, I don't like the use of rdfs:comment or skos:note to specify semantic data (even literals), as opposed to data used as a guide to human readers. 

@melanieWacker If specifyingSupplementaryContent indicates only that the content is present, perhaps a simple name change would help. To me, "specifying X" means actually giving the information. Does 504$6 "linkage" allow a link to the supplementary content? In that case, this could be a narrower term of oa:linking. I can't think of a great term right now - maybe linkingToSupplementaryContent? However, suppose the link won't always be present so I suppose this probably won't work.

**Comment by rjyounes** [comment]
Regarding the examples above provided by @melanieWacker: the first simply points to the existence of the data, whereas the second apparently provides the data. Perhaps that difference could be captured by an Annotation consisting of a link, vs one with a textual body.

**Comment by eslao** [comment]
@rjyounes Understood. I think @sfolsom's point was not that rdfs:comment was the only way to do it, but that the subject should be the entity that's being described and not the resource that the entity happened to produce.

**Comment by rjyounes** [comment]
Conclusions from 6/26 meeting with Melanie, Amber, Rebecca, and Javed:

- Rename specifyingSupplementaryContent to describingSupplementaryContent, since the annotation does not itself provide the content but rather points to it or indicates that it exists. See, e.g., specifyingCustodialHistory, which actually provides the custodial history rather than pointing to a source of data.

- specifyingBibliographicData and specifyingAdministrativeData: these are used to provide information about agents attached to a bib resource via an Activity, depending on the value of the first indicator (0 for person, 1 for organization). We will not implement these motivations, but rather recommend that (a) in original cataloging the information will be either attached to the agent or available through linkage to an external entity (b) in conversion/mapping, the MARC literal will be handled as legacy data on the agent: added to an rdfs:comment field with datatype bdt:legacySourceData.
