### ISSUE TITLE
Additional metadata for the ontology

### ISSUE THREAD

**Issue by sfolsom** [ld4l-labs/ontology#48]
Add the following assertions about the ontology

<dcterms:title xml:lang="en">bibliotek-o: a BIBFRAME 2 Ontology Extension</dcterms:title>
<voaf:extends rdf:resource="http://id.loc.gov/ontologies/bibframe/"/>
<voaf:specializes rdf:resource="http://id.loc.gov/ontologies/bibframe/"/>

Future consideration for voaf:useageInDataset and foaf:mbox if we can decide how/if we want to communicate outside of git repo functionalities.

**Comment by rjyounes** [comment]
I'm a bit confused about the way voaf defines these terms: Domain and range are both specified as voaf:Vocabulary, which is a subset of void:Dataset. Granted there's nothing in the definition of the latter ("set of RDF triples") that precludes an ontology being a dataset, it seems odd. I don't understand the intent in voaf: the predicates clearly refer to ontology assertions rather than instance data.

**Comment by rjyounes** [comment]
See commit 60fb46a0.

**Comment by rjyounes** [comment]
Additional discussion:

Steven: My sense of voaf is that when it says Dataset, it's not making a distinction between Tbox/Abox. I've seen examples of use relating one ontology to another, but I need to find it again. the name is a little misleading, but the definitions make it clearer.

Rebecca: The void spec https://www.w3.org/TR/void/ gives the dbpedia dataset as an ex of a Dataset. Based on dbpedia's description of its datasets at http://wiki.dbpedia.org/Downloads2015-10#datasets, I'm not convinced that it includes an ontology. For example, they say "The ontology version used while extracting all datasets can be downloaded here:"

Rebecca: Though I agree that the defs of voaf:extends and voaf:specializes indicate that they deal with ontologies rather than what we typically think of as dataset. Are we clear on the status of voaf as an accepted standard? Sorry if that's an ignorant question, but I haven't heard of it before.

**Comment by sfolsom** [comment]
Here's a nice article about LOV and it's use of voaf. Seems like how we're imagining using it is exactly what they would expect. http://www.semantic-web-journal.net/system/files/swj1127.pdf

**Comment by rjyounes** [comment]
OK, thanks. I'll close the issue.
